### ISSUE TITLE
 Missing Edges on export to CSV.

### ISSUE THREAD

**Issue by Andreas4242** [rust-transit/osm4routing2#47]
Hello,

I am encountering an issue with missing edges when using the “dach-latest.osm.pbf” file from Geofabrik. 
Specifically, certain edges such as osm_id 31453973, 141492345, and 772949108 are not present, even though I can find them when importing the same file using osm2pgsql.

Those edges are secondary-links.
For example: 

https://www.openstreetmap.org/way/31453973

I did not used --merge-edges option while creating the CSV files.

Could someone please help me understand why this discrepancy is occurring?

Thank you.

https://download.geofabrik.de/europe/dach.html

**Comment by Tristramg** [comment]
Thank you for pointing this error. It was due to the fact that roads tagged as secondary_link where ignored (while relatively common https://taginfo.openstreetmap.org/keys/highway#values)

It should be fixed as soon as I merge the PR
